/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica_mp3;

import com.mpatric.mp3agic.*;
import com.mpatric.mp3agic.Mp3File;
import java.awt.Image;

import java.io.File;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author yesen
 */
public class datos extends javax.swing.JFrame {

    Mp3File mp3file;
    ID3v2 id3v2Tag;
    String cancion;

    File archivo;
    Media audio;
    MediaPlayer reproductor;

    public datos() {
        initComponents();
    }

    private void LimpiarCampos() {
        txtAlbum.setText(null);
        txtArtista.setText(null);
        txtBitrate.setText(null);
        txtCancion.setText(null);
        txtDuracion.setText(null);
        txtID3v1.setText(null);
        txtID3v2.setText(null);
        txtSample.setText(null);
        txtTam.setText(null);
        txtTipo.setText(null);
        txtTitulo.setText(null);
        lPortada.setIcon(null);
    }

    public static void main(String[] args) throws Exception {
        datos objD = new datos();
        objD.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBitrate = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtID3v2 = new javax.swing.JTextField();
        txtSample = new javax.swing.JTextField();
        txtID3v1 = new javax.swing.JTextField();
        txtCancion = new javax.swing.JTextField();
        txtTam = new javax.swing.JTextField();
        txtAlbum = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtArtista = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lPortada = new javax.swing.JLabel();
        btnReproducir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel2.setText("Bitrate");

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel3.setText("#Canción");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel4.setText("Duración");

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel5.setText("Sample rate");

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel6.setText("¿ID3v1?");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel7.setText("¿ID3v2?");

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel8.setText("Artista");

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel9.setText("Álbum");

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel10.setText("Título");

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel11.setText("Tipo de imagen");

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel12.setText("Tamaño de imagen");

        btnActualizar.setBackground(new java.awt.Color(243, 239, 239));
        btnActualizar.setFont(new java.awt.Font("Roboto Medium", 3, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(243, 239, 239));
        btnStop.setFont(new java.awt.Font("Roboto Medium", 3, 18)); // NOI18N
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(243, 239, 239));
        btnBuscar.setFont(new java.awt.Font("Roboto Medium", 3, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBitrate.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtBitrate.setForeground(new java.awt.Color(102, 102, 102));
        txtBitrate.setToolTipText("");

        txtDuracion.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtDuracion.setForeground(new java.awt.Color(102, 102, 102));
        txtDuracion.setToolTipText("");

        txtID3v2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtID3v2.setForeground(new java.awt.Color(102, 102, 102));
        txtID3v2.setToolTipText("");

        txtSample.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtSample.setForeground(new java.awt.Color(102, 102, 102));
        txtSample.setToolTipText("");

        txtID3v1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtID3v1.setForeground(new java.awt.Color(102, 102, 102));
        txtID3v1.setToolTipText("");

        txtCancion.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtCancion.setForeground(new java.awt.Color(102, 102, 102));
        txtCancion.setToolTipText("");

        txtTam.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtTam.setForeground(new java.awt.Color(102, 102, 102));
        txtTam.setToolTipText("");

        txtAlbum.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtAlbum.setForeground(new java.awt.Color(102, 102, 102));
        txtAlbum.setToolTipText("");

        txtTitulo.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(102, 102, 102));
        txtTitulo.setToolTipText("");

        txtTipo.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(102, 102, 102));
        txtTipo.setToolTipText("");

        txtArtista.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtArtista.setForeground(new java.awt.Color(102, 102, 102));
        txtArtista.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        lPortada.setBackground(new java.awt.Color(255, 204, 255));
        lPortada.setForeground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lPortada, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnReproducir1.setBackground(new java.awt.Color(243, 239, 239));
        btnReproducir1.setFont(new java.awt.Font("Roboto Medium", 3, 18)); // NOI18N
        btnReproducir1.setText("Play");
        btnReproducir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(239, 239, 239)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtBitrate, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtID3v2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSample, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtID3v1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnReproducir1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar)
                                .addGap(57, 57, 57)
                                .addComponent(btnActualizar)
                                .addGap(81, 81, 81))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(btnStop)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBitrate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSample, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtID3v1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtID3v2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnActualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReproducir1)
                    .addComponent(btnStop))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mp3_fun(String cancion) throws Exception {
        // Lee el MP#
        mp3file = new Mp3File("src/audios/"+cancion);

        txtDuracion.setText(mp3file.getLengthInSeconds() + " segundos");
        txtBitrate.setText(mp3file.getBitrate() + " kbps " + (mp3file.isVbr() ? "(VBR)" : "(CBR)"));
        txtSample.setText(mp3file.getSampleRate() + " Hz");
        txtID3v1.setText(mp3file.hasId3v1Tag() ? "SI" : "NO");
        txtID3v2.setText(mp3file.hasId3v2Tag() ? "SI" : "NO");

        // Nos importa si tiene etiqueta DI3V2
        if (mp3file.hasId3v2Tag()) {
            id3v2Tag = mp3file.getId3v2Tag();
            txtCancion.setText(id3v2Tag.getTrack());
            txtArtista.setText(id3v2Tag.getArtist());
            txtTitulo.setText(id3v2Tag.getTitle());
            txtAlbum.setText(id3v2Tag.getAlbum());

            byte[] albumImageData = id3v2Tag.getAlbumImage();

            // Si tiene carÃ¡tula guara la caratula como una imÃ¡gen JPG
            if (albumImageData != null) {
                txtTam.setText(albumImageData.length + " bytes");
                txtTipo.setText(id3v2Tag.getAlbumImageMimeType());

                ImageIcon imagen = new ImageIcon(albumImageData);
                Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lPortada.getWidth(), lPortada.getHeight(), Image.SCALE_DEFAULT));
                lPortada.setIcon(icono);
            }
        }
        txtDuracion.setEditable(false);
        txtBitrate.setEditable(false);
        txtSample.setEditable(false);
        txtID3v1.setEditable(false);
        txtID3v2.setEditable(false);
        txtTam.setEditable(false);
        txtTipo.setEditable(false);
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        cancion = JOptionPane.showInputDialog("Introduce el nombre de la canción");
        cancion = cancion + ".mp3";
        try {
            mp3_fun(cancion);
        } catch (Exception ex) {
            Logger.getLogger(datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        reproductor.stop();
    }//GEN-LAST:event_btnStopActionPerformed

    public void act_mp3() throws Exception {
        id3v2Tag.setTrack(txtCancion.getText());
        id3v2Tag.setArtist(txtArtista.getText());
        id3v2Tag.setTitle(txtTitulo.getText());
        id3v2Tag.setAlbum(txtAlbum.getText());
        
       String x;
        x = JOptionPane.showInputDialog("¿Desea cambiar/asignar una portada (SI/NO)");
        x=x.toUpperCase();
        if("SI".equals(x)){
            String imagen = JOptionPane.showInputDialog("Introduce el nombre de la imagen");
            File ima = new File("src/images/"+imagen);
            byte[] bytesI = Files.readAllBytes(ima.toPath());
            id3v2Tag.setAlbumImage(bytesI,id3v2Tag.getAlbumImageMimeType());

             byte[] albumImageData2 = id3v2Tag.getAlbumImage();

            // Si tiene carÃ¡tula guara la caratula como una imÃ¡gen JPG
            if (albumImageData2 != null) {

                ImageIcon imagen1 = new ImageIcon(albumImageData2);
                Icon icono = new ImageIcon(imagen1.getImage().getScaledInstance(lPortada.getWidth(), lPortada.getHeight(), Image.SCALE_DEFAULT));
                lPortada.setIcon(icono);
            }
        }
        String nuevoC;
        nuevoC = JOptionPane.showInputDialog("Introduce el nombre de la canción editada");
        nuevoC = nuevoC + ".mp3";
        mp3file.save("src/audios/"+nuevoC);

    }

    int bandera;
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            act_mp3();
            LimpiarCampos();
            if(bandera==1){
            reproductor.pause();
            }
        } catch (Exception ex) {
            Logger.getLogger(datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnReproducir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducir1ActionPerformed
        // TODO add your handling code here:
        com.sun.javafx.application.PlatformImpl.startup(() -> {
        });
        final String nombreA = cancion;
        archivo = new File("src/audios/"+nombreA);
        audio = new Media(archivo.toURI().toString());
        reproductor = new MediaPlayer(audio);
        reproductor.play();
        bandera=1;
    }//GEN-LAST:event_btnReproducir1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnReproducir1;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lPortada;
    private javax.swing.JTextField txtAlbum;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtBitrate;
    private javax.swing.JTextField txtCancion;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtID3v1;
    private javax.swing.JTextField txtID3v2;
    private javax.swing.JTextField txtSample;
    private javax.swing.JTextField txtTam;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
